### ISSUE TITLE
Why is there a difference in manifest here and on add-on site

### ISSUE THREAD

**Issue by sleek22** [mrdokenny/History-AutoDelete#15]
I'm on pcxFirefox which is 64-bit. Some of the last few add-ons I've tried to install won't install and give a "...appears to be corrupt" message. Same for this add-on from the Firefox site.

I noticed a difference and copied the manifest.json from this version into the Firefox version and it installed perfectly and is working fine. This is an amazing add-on! Thank you to the developer.

The lines missing in the Firefox version manifest appears to be the following:

"applications": {
    "gecko": {
      "id": "mrdokenny@gmail.com"
    }

Can someone please explain why there is a difference and why it is missing in the Firefox version?

Update: When I tried downloading from here and zipping the contents and renaming as a xpi file, I get the same error message as before, i.e., can't install.

Another Update: I think this is a problem in the current version of Firefox I am using (version 50.1.0). I believe it has been fixed in Firefox 51.

According to this website:

https://8pecxstudios.com/Forums/viewtopic.php?f=5&t=1663&start=10

**Comment by mrdokenny** [comment]
Hey thanks for liking my addon. I didn't include an ID because I thought that I didn't need it. So the AMO website just auto generated an ID for me. Now that it appears that I need to put that auto generated ID in the manifest to suppress some warnings with the addon validator. This will come in the next version.
